# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). 
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.host_name = "ucla-vagrant" 

  config.vm.synced_folder ".", "/source"

  config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 2
  end

  config.vm.provision :shell, :path => "provision.sh"
end
